version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  assignees:
    - "modem7"
  labels:
  - dependencies
  commit-message:
    prefix: fix
    include: scope
