version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  labels:
  - dependencies
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: gradle
  directory: "/tests"
  schedule:
    interval: daily
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
