---

kind: pipeline
type: docker
name: latest

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint Dockerfile*

- name: Latest  
  image: plugins/docker
  privileged: true
  settings:
    repo: modem7/docker-grafana
    purge: true
    compress: true
    use_cache: true
    build_args: BUILDKIT_INLINE_CACHE=1
    cache_from: "modem7/docker-grafana:latest"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - 9.0.3

- name: pushrm-dockerhub
  image: chko/docker-pushrm
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASS:
      from_secret: docker_password
    PUSHRM_FILE: README.md
    PUSHRM_SHORT: Repack of Grafana with the usual Homecentr bells and whistles.
    PUSHRM_TARGET: modem7/docker-grafana
  when:
    status:
      - success

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom
